(function(d){var h=[];d.loadImages=function(a,e){"string"==typeof a&&(a=[a]);for(var f=a.length,g=0,b=0;b<f;b++){var c=document.createElement("img");c.onload=function(){g++;g==f&&d.isFunction(e)&&e()};c.src=a[b];h.push(c)}}})(window.jQuery);
var wl;

ldsrcset=function(t){var e,r=document.querySelectorAll(t);for(e=0;e<r.length;e++){var c=r[e].getAttribute("data-srcset");r[e].setAttribute("srcset",c)}},ldsrc=function(t){var e=document.querySelector(t);if(e){var r=e.getAttribute("data-src");e.setAttribute("src",r)}};ldv=function(t){var e=document.querySelector(t);if(e){var r=document.querySelector(t+" source"),c=r.getAttribute("data-src");r.setAttribute("src",c),e.load()}};!function(){if("Promise"in window&&void 0!==window.performance){var e,t,r=document,n=function(){return r.createElement("link")},o=new Set,a=n(),i=a.relList&&a.relList.supports&&a.relList.supports("prefetch"),s=location.href.replace(/#[^#]+$/,"");o.add(s);var c=function(e){var t=location,r="http:",n="https:";if(e&&e.href&&e.origin==t.origin&&[r,n].includes(e.protocol)&&(e.protocol!=r||t.protocol!=n)){var o=e.pathname;if(!(e.hash&&o+e.search==t.pathname+t.search||"?preload=no"==e.search.substr(-11)||".html"!=o.substr(-5)&&".html"!=o.substr(-5)&&"/"!=o.substr(-1)))return!0}},u=function(e){var t=e.replace(/#[^#]+$/,"");if(!o.has(t)){if(i){var a=n();a.rel="prefetch",a.href=t,r.head.appendChild(a)}else{var s=new XMLHttpRequest;s.open("GET",t,s.withCredentials=!0),s.send()}o.add(t)}},p=function(e){return e.target.closest("a")},f=function(t){var r=t.relatedTarget;r&&p(t)==r.closest("a")||e&&(clearTimeout(e),e=void 0)},d={capture:!0,passive:!0};r.addEventListener("touchstart",function(e){t=performance.now();var r=p(e);c(r)&&u(r.href)},d),r.addEventListener("mouseover",function(r){if(!(performance.now()-t<1200)){var n=p(r);c(n)&&(n.addEventListener("mouseout",f,{passive:!0}),e=setTimeout(function(){u(n.href),e=void 0},80))}},d)}}();

$(function(){
r=function(){dpi=window.devicePixelRatio;var a='data-src';var e=document.querySelector('.un17');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/1280px-gibson_logo.svg-1074.png':'images/1280px-gibson_logo.svg-716.png'):'images/1280px-gibson_logo.svg-358.png');
var a='data-src';var e=document.querySelector('.un18');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?'images/ibanez_logo.svg-1194.png':'images/ibanez_logo.svg-597.png');
var a='data-src';var e=document.querySelector('.un19');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/2560px-jackson_guitars_logo.svg-1746.png':'images/2560px-jackson_guitars_logo.svg-1164.png'):'images/2560px-jackson_guitars_logo.svg-582.png');

var a='data-src';var e=document.querySelector('.un21');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/stacked-pink-ernie-ball-logo-sticker-ernie-ball-115632918897lz0eztvsb-723.png':'images/stacked-pink-ernie-ball-logo-sticker-ernie-ball-115632918897lz0eztvsb-482.png'):'images/stacked-pink-ernie-ball-logo-sticker-ernie-ball-115632918897lz0eztvsb-241.png');

var a='data-src';var e=document.querySelector('.un23');if(e.hasAttribute('src')){a='src';}e.setAttribute(a,(dpi>1)?((dpi>2)?'images/img_1467-516.png':'images/img_1467-344.png'):'images/img_1467-172.png');
var e=document.querySelector('.un13');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/30665de7-3283-40ca-a9ed-b3591476a9aa-615.jpeg':'images/30665de7-3283-40ca-a9ed-b3591476a9aa-410.jpeg'):'images/30665de7-3283-40ca-a9ed-b3591476a9aa-205.jpeg');
var e=document.querySelector('.un14');e.setAttribute('src',(dpi>1)?'images/brand-hansen-music-marshall-amps-1214.png':'images/brand-hansen-music-marshall-amps-607.png');
var e=document.querySelector('.un15');e.setAttribute('src',(dpi>1)?((dpi>2)?'images/327421-1653.png':'images/327421-1102.png'):'images/327421-551.png');};
if(!window.HTMLPictureElement){r();}
!function(){var e=document.querySelectorAll('a[href^="#"]');[].forEach.call(e,function(e){e.addEventListener("click",function(t){var o=0;if(e.hash.length>1){var n=parseFloat(getComputedStyle(document.body).getPropertyValue("zoom"));n||(n=1);var r=document.querySelectorAll('[name="'+e.hash.slice(1)+'"]')[0];if(!r)return;var l=/chrome/i.test(navigator.userAgent);o=l?r.getBoundingClientRect().top*n+pageYOffset:(r.getBoundingClientRect().top+pageYOffset)*n}if("scrollBehavior"in document.documentElement.style)scroll({top:o,left:0,behavior:"smooth"});else if("requestAnimationFrame"in window){var a=pageYOffset,i=null;requestAnimationFrame(function e(t){i||(i=t);var n=t-i;scrollTo(0,a<o?(o-a)*n/400+a:a-(a-o)*n/400),n<400?requestAnimationFrame(e):scrollTo(0,o)})}else scrollTo(0,o);t.preventDefault()},!1)})}();
initMenu($('#m1')[0]);
$('.c67').Stickyfill();
if(location.hash){var e=location.hash.replace("#",""),o=function(){var t=document.querySelectorAll('[name="'+e+'"]')[0];t&&t.scrollIntoView(),"0px"===window.getComputedStyle(document.body).getPropertyValue("min-width")&&setTimeout(o,100)};o()}

});lfn=function(){ldsrcset('.un24 source');ldsrcset('.un25 source');ldsrcset('.un26 source');ldsrcset('.un27 source');ldsrcset('.un28 source');ldsrcset('.un29 source');ldsrcset('.un30 source');ldsrcset('.un31 source');};if(document.readyState=="complete"){lfn();}else{$(window).on("load",lfn);}